### ISSUE TITLE
Problem with target data file (2023-10-27)

### ISSUE THREAD

**Issue by paulocv** [HopkinsIDD/rsv-forecast-hub#80]
The `value` column of `target-data/archive/2023-10-27_rsvnet_hospitalization.csv` is filled with `NA`s. The problem starts on row 70955 and lasts until the end of the file.

```
.
.
.
"49",2023-10-21,"50-64","inc hosp",0,479817
"49",2023-10-07,"65-130","rate hosp",0,405200
"49",2023-10-07,"65-130","inc hosp",0,405200
"49",2023-10-14,"65-130","rate hosp",0,405200
"49",2023-10-14,"65-130","inc hosp",0,405200
"49",2023-10-21,"65-130","rate hosp",0,405200
"49",2023-10-21,"65-130","inc hosp",0,405200
"06",2014-10-11,"0-0.49","rate hosp",NA,249617
"06",2014-10-11,"0-0.49","inc hosp",NA,249617
"06",2014-10-18,"0-0.49","rate hosp",NA,249617
"06",2014-10-18,"0-0.49","inc hosp",NA,249617
"06",2014-10-25,"0-0.49","rate hosp",NA,249617
"06",2014-10-25,"0-0.49","inc hosp",NA,249617
"06",2014-11-01,"0-0.49","rate hosp",NA,249617
.
.
.
```

**Comment by kjsato** [comment]
@paulocv Thanks for your reporting. These target-data files refer to the same data as the ones in [rsv-scenario-modeling-hub/](https://github.com/midas-network/rsv-scenario-modeling-hub/tree/main/target-data) and there are NAs in the original data either. Please let us leave them as they are without modifying it.

**Comment by kjsato** [comment]
This is gonna be closed
