### ISSUE TITLE
65-130 age group?

### ISSUE THREAD

**Issue by tkcy** [HopkinsIDD/rsv-forecast-hub#96]
Hi! It may be an issue on my end, but is there a problem with the 65-130 age group in the target data this week (ie. is it missing)? Thanks!

**Comment by kimberlynroosa** [comment]
Hi @tkcy ! Thank you for bringing this to our attention. We will look into this issue further. For now, I have added a new data file (labeled _update) that contains 65+ using the difference between the all ages and the other age groups.

**Comment by tkcy** [comment]
Thank you! Scenario modeling hub is also investigating and suggested the name of the age group may have changed in the source file (I don't know how much if any overlap there is between the two groups!)

**Comment by kimberlynroosa** [comment]
Thanks! I talked with Luci from SMH, and the name had changed. The appropriate file is now uploaded!

**Comment by tkcy** [comment]
@kimberlynroosa Thanks so much for the update! I see that 65-74 has now been added, which still leaves a gap for ages 75+.  In the raw file from RSV-Net I believe I see 75-84.  Perhaps if RSV-Net is permanently discontinuing the 65-130 group, the hub input file could add the 65-74s? But I'm hoping it's temporary and they bring back the entire age range.
